revision: 1
schema-version: 1
owner-ms-alias: adegeo

config:
  DocMetadata:
    Headers:
      - ["---", "#### "]

    ParserRegex: "^\\* (.*): (.*)$"

issues:

  opened:
    # New issue opened, add Not Triaged  
    - labels-add: [":watch: Not Triaged"]


    # default for doc comment
    - check:
        - type: metadata-exists
      pass:
        - labels-add: ["Source - Docs.ms"]

        # technology types
        - check:
            - type: metadata-comment
              name: technology
              value: "(?i)aspnetcore-blazor$"
          pass:
            - labels-add: ["Blazor"]
        - check:
            - type: metadata-comment
              name: technology
              value: "(?i)aspnetcore-grpc$"
          pass:
            - labels-add: ["gRPC"]
        - check:
            - type: metadata-comment
              name: technology
              value: "(?i)aspnetcore-signalr$"
          pass:
            - labels-add: ["SignalR"]

        # Checks for specific files
        - check:
            - type: metadata-comment
              name: contentsource
              value: "(?i).*main\/aspnetcore\/mvc\/views\/tag-helpers\/built-in\/component-tag-helper.md"
          pass:
            - labels-add: ["Blazor"]
        
        # If the word appears anywhere in the file name path, add the label
        - check:
            - type: metadata-comment
              name: contentsource
              value: "(?i).*blazor.*"
          pass:
            - labels-add: ["Blazor"]
        - check:
            - type: metadata-comment
              name: contentsource
              value: "(?i).*grpc.*"
          pass:
            - labels-add: ["gRPC"]
        - check:
            - type: metadata-comment
              name: contentsource
              value: "(?i).*signalr.*"
          pass:
            - labels-add: ["SignalR"]

  labeled:

    # If a blazor label is added to an issue, automatically add it to the blazor project
    - check:
        - type: query
          value: "length(Issue.labels[?name == 'Blazor']) != `0`"
      pass:
        - projects-add: [35]
